# Generated by Django 4.1.7 on 2023-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_category_slug_alter_fooditem_food_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food_title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
