# Generated by Django 4.1 on 2023-02-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MTN', 'MTN'), ('Vodafone', 'Vodafone'), ('AirtelTigo', 'AirtelTigo'), ('VISA', '    VISA'), ('PayPal', 'PayPal')], max_length=100),
        ),
    ]
