# Generated by Django 4.1.4 on 2023-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0007_alter_openinghour_options_and_more'),
        ('orders', '0002_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedfood',
            name='vendors',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
    ]
